---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
# image will be published to ghcr.io/<user>/<name>
name: bluefin-displaylink-amd
# description will be included in the image's metadata
description: A bluefin image with evdi, displaylink and amdgpu

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/ublue-os/bluefin-dx
image-version: 41 # latest is also supported if you want new updates ASAP

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  - type: files
    files:
      - source: system
        destination: /

  - type: rpm-ostree
    repos:
      - https://negativo17.org/repos/fedora-multimedia.repo

  - type: akmods
    base: extra
    install:
      - evdi

  - type: default-flatpaks
    notify: true 
    system:
      install:
        - org.mozilla.firefox

  - type: signing 
